export const GET_USERS_NAME = 'GET_USERS_NAME';
export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_SINGLE_USER_FAIL = 'GET_SINGLE_USER_FAIL';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';